service: finalprojectcopy 

frameworkVersion: '3'
  
provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1

functions: 
  hello:
    handler: handler.hello
    # Setup Lambda Trigger
    events:
      - http:
          method: post
          path: hello
  